# Generated by Django 5.2.6 on 2025-10-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название заголовка",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Напишите свой контент",
                        null=True,
                        verbose_name="Контент",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        help_text="Добавьте изображение",
                        upload_to="my_blog/photo",
                        verbose_name="Фото превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Введите дату создания блога",
                        null=True,
                        verbose_name="Дата создания",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "count_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заголовок",
                "verbose_name_plural": "Заголовоки",
                "ordering": ["title", "created_at"],
            },
        ),
    ]
