# Generated by Django 5.2.6 on 2025-10-04 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_category",
                    models.CharField(
                        help_text="Название Категории",
                        max_length=100,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "description_category",
                    models.TextField(
                        help_text="Описание категории", verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name_category"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_product",
                    models.CharField(
                        help_text="Название продукта",
                        max_length=100,
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "description_product",
                    models.TextField(
                        help_text="Описание продукта", verbose_name="Описание"
                    ),
                ),
                (
                    "photo_product",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото продукта",
                        null=True,
                        upload_to="catalog/photo",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "unit_price_product",
                    models.IntegerField(help_text="Цена за покупку"),
                ),
                (
                    "created_at",
                    models.DateField(
                        help_text="Введите дату создания продукта",
                        verbose_name="Дата создания",
                    ),
                ),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "category_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите категорию",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": [
                    "name_product",
                    "unit_price_product",
                    "created_at",
                    "updated_at",
                ],
            },
        ),
    ]
