# Generated by Django 5.2.6 on 2025-10-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_country",
                    models.CharField(
                        help_text="Страна", max_length=100, verbose_name="Контакт"
                    ),
                ),
                (
                    "inn_company",
                    models.TextField(help_text="Инн компании", verbose_name="Описание"),
                ),
                (
                    "adr_contact",
                    models.TextField(
                        help_text="Адрес компании и телефон", verbose_name="Номер"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["name_country"],
            },
        ),
    ]
