# Generated by Django 5.2.6 on 2025-10-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_price_product",
            field=models.IntegerField(
                help_text="Цена за покупку", verbose_name="Цена за один товар"
            ),
        ),
    ]
