# Generated by Django 4.2.2 on 2025-10-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": [
                    "name_product",
                    "unit_price_product",
                    "created_at",
                    "updated_at",
                ],
                "permissions": [
                    ("can_unpublish_product", "Отмена публикации продукта")
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_publicate",
            field=models.BooleanField(
                default=False,
                help_text="Укажите статус публикации",
                verbose_name="Статус публикации",
            ),
        ),
    ]
